name = "PTM2"
author = "Pranav Taysheti"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f6704d7117f5bac4d9ec1fe2b7a33e4e1a6d2e2566c7c295580dc077d21f468"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
