name = "PTM2"
author = "Pranav Taysheti"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5be4d19468655e31662fc371221385c64ac3358db28623cafc3765f0bd860b9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
