name = "PTM2"
author = "Pranav Taysheti"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cef27a4b0f86e43f5c48f1b7a8bb815decb1c8720e758ed5d569a773a3ea88e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
